# Generated by Django 3.1.1 on 2020-09-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfil',
                'ordering': ['id'],
            },
        ),
    ]
