# Generated by Django 3.1.1 on 2020-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='photos')),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tiendas',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'tienda',
                'ordering': ['id'],
            },
        ),
    ]
