# Generated by Django 3.0 on 2020-09-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('imagen', models.ImageField(blank=True, upload_to='photo/')),
                ('texto_corto', models.TextField(max_length=200, verbose_name='Extracto')),
                ('detalle', models.TextField(max_length=1000, verbose_name='Información del producto')),
                ('precio', models.FloatField()),
                ('avalible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
