# Generated by Django 3.1.1 on 2020-09-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_remove_producto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
